version: '2.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./:/app
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all  # Use all GPUs
            capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
